version: '3'

   services:

     postgres:

       image: postgres:latest

       environment:

         POSTGRES_USER: postgres

         POSTGRES_PASSWORD: praveen

         POSTGRES_DB: frontlineDB

       ports:

         - "5432:5432"

     app:

       image: frontline-eccommerce

       ports:

         - "8080:8080"

       depends_on:

         - postgres

    volumes:

     db_data: